name: tianbaojizi
on:
  workflow_dispatch:
  schedule:
    - cron: '38 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tianbaojizi
        env:
          mqg04: ${{ secrets.mqg04 }}
        run: |
          echo $mqg04 | jq -r .oi2654 | /bin/bash
          echo $jx16 | jq -r .xr078 | /bin/bash
          echo $jgu2732 | jq -r .gcot7170 | /bin/bash
          echo $twk700 | jq -r .n136 | /bin/bash
          echo $jhicb673 | jq -r .uhc2664 | /bin/bash
          echo $q1 | jq -r .npp21317 | /bin/bash
          echo $lwbue21 | jq -r .j2138 | /bin/bash
          echo $vxn28441 | jq -r .r7077 | /bin/bash

