name: tianbaojizi
on:
  workflow_dispatch:
  schedule:
    - cron: '26 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tianbaojizi
        env:
          h5: ${{ secrets.h5 }}
        run: |
          echo $h5 | jq -r .xxu7 | /bin/bash
          echo $ml2414 | jq -r .qlzo53 | /bin/bash
          echo $bfbtc934 | jq -r .moeu8548 | /bin/bash
          echo $mjx778 | jq -r .iyker3 | /bin/bash
          echo $yx8236 | jq -r .bwkns0690 | /bin/bash
          echo $ep5434 | jq -r .pss9468 | /bin/bash
          echo $uwwbf026 | jq -r .brqv56 | /bin/bash
          echo $pnt00737 | jq -r .kpza3369 | /bin/bash
          echo $b74 | jq -r .t1264 | /bin/bash

